### PR TITLE
Feature/urdf parser py

### PR DESCRIPTION
**Pull request by eacousineau**
From [this issue thread in robot_model_py](https://github.com/laas/robot_model_py/issues/4#issuecomment-20947614) - These changes incorporate urdf_parser_py, including newer features in the 'master' branch (currently supporting groovy / hyrdo).

I have run the unittests in calibration_estimation (the only package that seems to have depended on urdf_parser) and verified that there are no differences in running with these changes: [unittest comparison](https://github.com/eacousineau/calibration/blob/c619998fb3e5ae20a4c193884b949e69c4518a13/calibration_estimation/urdf_parser_py-unittests.txt)

### CODE REVIEW

**Comment by vrabaud** [comment]
ouh, I like that :) Good job, thx ! Does that need to be backported to groovy ?

**Comment by eacousineau** [comment]
Haha, thank you.
Yes, backporting to groovy would be nice -- I had tested these two packages in groovy.

**Comment by ahendrix** [comment]
No; we should not merge this into Groovy; Groovy is the stable release, and big changes like this should go into the next release.

**Comment by jonbinney** [comment]
@eacousineau thank you for fixing this!

**Comment by vrabaud** [comment]
So actually, has robot_model_py been released yet ? I think you forgot to add a dependency on that. No worries, I will add it once you release your package under Groovy/Hydro.

**Comment by vrabaud** [comment]
And also, if robot_model_py becomes a dependency, we should make it a core package and move it to ros-\* no ?

**Comment by eacousineau** [comment]
No, robot_model_py has not yet been released, but I can see if I can help Thomas Moulard make it a core package.
Thank you for adding the dependency!

**Comment by vrabaud** [comment]
please let me know if you need access to have it moved to ros-\* (ros what btw ? @isucan )

**Comment by isucan** [comment]
we should move it to robot_model, but we first need to separate it to its own package. should I do that? Then you can fix the calibration package?

**Comment by eacousineau** [comment]
When you say that it should be moved to its own separate package, do you mean `urdf_parser_py`?

**Comment by isucan** [comment]
Yes, the python urdf parser should be its own catkin package. I suggest we add it to the hydro-devel branch of robot_model:
https://github.com/ros/robot_model

**Comment by vrabaud** [comment]
@eacousineau  I'm gonna have to revert that pull request if the urdf_python issue is not solved before Hydro

**Pull request merged**
