### PR TITLE
Fixes RGBD detector

### PR DESCRIPTION
**Pull request by dgossow**
This fixes some issues with the Kinect-Based checkerboard detector used during capture:
- It was very sensitive to missing depth values, which is why it now estimates a plane and projects the corners onto that to determine a depth value for all of them
- It used a formula for computing the disparity for the virtual stereo pair which didn't make sense.

### CODE REVIEW

**Comment by dgossow** [comment]
Oh, one thing: the plane detection currently spams the console when it doesn't find the checkerboard plane:

```
[pcl::SampleConsensusModel::getSamples] Can not select 0 unique points out of 0!
[pcl::RandomSampleConsensus::computeModel] No samples could be selected!
[pcl::SACSegmentation::segment] Error segmenting the model! No solution found.
```

@jkammerl Do you know how to keep PCL from spamming stderr?

**Comment by ahendrix** [comment]
Seeing the depth to pointcloud code duplicated from rviz is ugly. I like the concept of converting the depth and RGB images to a pointcloud on an as-needed basis, but if that's going to come up more, we should probably push that code into a library. Is there a nodelet that already does this?

Everything else looks good! I'm going to trust you on the math.

**Comment by dgossow** [comment]
Yeah, the depth-to-pointcloud conversion _should_ be part of some standard ROS library. Don't know where this would go though.

Having this as a nodelet wouldn't work in this case since you only want to do the conversion for a small number of points.

**Comment by mikeferguson** [comment]
Looks good to me, but the default for "depth" topic in kinect_pipeline should be updated, it is no longer a topic called points typically.

**Comment by dgossow** [comment]
I would personally say that having a copy of julius' depth to points converter thingy in here is ok for now, since it doesn't have a home anywhere else at the moment. If we put it somewhere else this would probably add a dependency as well.

**Pull request merged**
