### PR TITLE
Multiple improvements and bugfixes to calibration

### PR DESCRIPTION
**Pull request by dgossow**

### CODE REVIEW

**Comment by ahendrix** [comment]
Please break this into multiple pull requests so that we can review the changes separately.

**Comment by mikeferguson** [comment]
It looks like you've broken most of these out -- did we do one for the "opt_runner: nicer console output"? That is a really nice fix.

**Comment by mikeferguson** [comment]
The "rgbd_cb_detector: commented out spammy console output" should probably be added to the rgbd pull request

**Comment by ahendrix** [comment]
Addressed by #8, #9, #10

**Pull request closed without merging**
